### ISSUE TITLE
Setup ceremony infrastructure

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci-phase2-setup#3]
- [ ] domain (subdomain pse)
- [ ] setup custom domain on Firebase hosting
- [x] host ceremony website (vercel + fleek) https://github.com/privacy-scaling-explorations/maci-phase2-setup/issues/1 -> migrated to Firebase hosting
- [x] create p0tion ceremony (firebase with p0tion)

**Comment by daodesigner** [comment]
requested PSE subdomain for P0tion
